# Generated by Django 5.2.1 on 2025-05-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=255,
                verbose_name="Account Status",
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="marrital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("in_a_relationship", "In a Relationship"),
                    ("engaged", "Engaged"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("complicated", "It's Complicated"),
                    ("prefer_not_to_say", "Prefer Not to Say"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
